### ISSUE TITLE
Firefox addon link doesn't work

### ISSUE THREAD

**Issue by Absolucy** [mcclure/NFTBlocker#4]
![image](https://user-images.githubusercontent.com/65794972/144723750-71394c54-2337-4a66-88b3-ce49f29f0055.png)

did it get mass reported or something

**Comment by mcclure** [comment]
Sorry-- if you'll look carefully at the README you'll see that is the page for the Twitter Block Chain plugin.

Maybe it did get mass reported. I would ask the [Twitter Block Chain](https://github.com/ceceradio/twitter-block-chain) github about that.

NFTBlocker is not yet on Firefox Store. You must get it from the Releases page and sideload it.
There is not much reason to do this yet except for testing tho because the NFT feature which NFTBlocker blocks is still in beta.
Once the feature goes public I will try to add NFTBlocker to the store.

**Comment by Absolucy** [comment]
Ah, alright.
